name: Deploy to Production

on:
  push:
    branches:
      - 'website'

# It is important to specify "concurrency" for the workflow,
# to prevent concurrency between different deploys.
concurrency: production_environment

jobs:
  deploy:
    name: Deploy code to prod
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Deploy
      uses: deployphp/action@v1
      with:
        deployer-version: "7.3.0"
        dep: deploy prod -f .github/deploy.php
        private-key: ${{ secrets.PRIVATE_KEY }}