# Updates the submodules in the website branch
name: Website

on:
  push:
    branches: [ master, develop, '4.*', '5.*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: website
          token: ${{ secrets.CHECKOUT_TOKEN }}
      
      - name: Update submodule
        run:  git submodule update --init --remote --merge

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with: 
          author_name: Github Actions
          author_email: github-actions@github.com
          branch: website
          message: 'Updating submodules'
